### ISSUE TITLE
add grafana monitor addon

### ISSUE THREAD

**Issue by jolestar** [QingCloudAppcenter/kubernetes#7]
https://github.com/grafana/grafana

**Comment by martinyunify** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [use grafana as default dashboard](https://trello.com/c/Anj8XqbC/8-use-grafana-as-default-dashboard)

**Comment by martinyunify** [comment]
close because we have prometheus installed. and user application can be monitored through prometheus
